# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".ruff_cache",
    "buck-out",
    "venv",
    "analytics",
    "*.log",
    ".gitgnore"
]

line-length = 120
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[lint]
select = [
    "E4",
    "E7",
    "E9",
    "A",    # prevent using keywords that clobber python builtins
    "B",    # bugbear: security warnings
    "E",    # pycodestyle
    "F",    # pyflakes
    "ISC",  # implicit string concatenation
    "UP",   # alert you when better syntax is available in your python version
    # "RUF",  # the ruff developer's own rules
]

ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []


[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"