name: Build, Push, Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy to'
        required: true
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  build-push:
    name: Build docker image
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: "Set current date as env variable"
      run: |
        echo "builddate=$(date +'%Y.%m.%d-%H-%M-%S')" >> $GITHUB_OUTPUT
      id: version  # this is used on variable path
        
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Log in our registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/tw/nats/nats-to-telegram:${{ steps.version.outputs.builddate }}-${{ github.event.inputs.environment }}
        labels: ${{ steps.meta.outputs.labels }}
